name: Windows Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Windows Build
    permissions: write-all
    runs-on: windows-latest
    steps:
      - name: Retrieving latest commit.
        uses: actions/checkout@v4

      - name: Setting up Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.7

      - name: Display current Haxe Version
        run: haxe -version

      - name: Installing libraries
        run: |
          haxe -cp cli --run Lib

      - name: Building the game
        run: |
          haxelib run lime build windows

      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        with:
          name: LineTapper
          path: export/windows/bin
